### ISSUE TITLE
Bump requests version

### ISSUE THREAD

**Issue by max-arnold** [odynvolk/pinterest-pinata#1]
Hi! Can you please bump `requests` version to more recent? For example `install_requires=["requests>=2.5.0"]`.

**Comment by odynvolk** [comment]
Hello there!

Sorry for the wait. I just updated it now.

Thanks for the suggestion!

**Comment by ydaniels** [comment]
Hi i keep getting Something went terribly wrong HTTP Error 400: BAD REQUEST

**Comment by ydaniels** [comment]
And i dont think username is compulsory

**Comment by max-arnold** [comment]
> i keep getting Something went terribly wrong HTTP Error 400: BAD REQUEST

This is probably unrelated to this issue. Most likely this is due to rate limits (wait for about an hour and insert time.sleep(15) between your image upload attempts).

**Comment by ydaniels** [comment]
okay thanks

**Comment by odynvolk** [comment]
Like max-arnold says it probably due to rate limits, I've received it myself a couple of times. Don't send too many and you'll be fine.
