### ISSUE TITLE
HTTP Error 403: FORBIDDEN

### ISSUE THREAD

**Issue by ydaniels** [odynvolk/pinterest-pinata#2]
Why do i keep getting something terribly went wrong  HTTP Error 403: FORBIDDEN
when i try to follow user

**Comment by ydaniels** [comment]
Okay all your request should be to https://ww.pinterest.com not the unsecured one. I fixed it

**Comment by ydaniels** [comment]
now facing another problem. I think it does not work at all, you have to pass a csrftoken before login.
which means you have to visit pinterest page first to get cookies, then you can now obtain a  csrftoken.
I keep getting a json response containing html page complaing about CsrfErrorPage Module Oh no! Pinterest doesn't work unless you <a href="http://enable-javascript.com/" rel="nofollow">turn on JavaScript.</a></div>
.
I just want to confirm if it has not broken.

**Comment by odynvolk** [comment]
Hi there!

Sorry for the very late reply. Pinterest have updated their site and it now requires JavaScript as you mention. Searching still seems to work, but not pinning/creation etc. 

Not sure if/when I will do something about it. I would probably have to use something else than urllib in Python.
