### ISSUE TITLE
Searchresult

### ISSUE THREAD

**Issue by FirstAVJohan** [odynvolk/pinterest-pinata#3]
Hi,

If I do a pinata.search_pins() I get 25 times the same result, no matter what query I use.
What can be wrong?

![screenshot_1](https://cloud.githubusercontent.com/assets/12291624/11243959/6a85fca6-8e0b-11e5-82dd-4e573d7a04f9.png)

**Comment by odynvolk** [comment]
Hi there!

Thanks for the report. I had an error in the parsing of the result. I just fixed it in the latest commit. I also improved the tests so this should be easier to spot in the future.
