### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by grayhuze** [odynvolk/pinterest-pinata#6]
can you provide and example of how to use your pinterest-pinata library.  Having a hard time getting it to work.  Looks promising though.

**Comment by odynvolk** [comment]
Hi there!

Sorry for the very late reply. Pinterest have updated their site and it now requires JavaScript as you mention. Searching still seems to work, but not pinning/creation etc. 

Not sure if/when I will do something about it. I would probably have to use something else than urllib in Python.
